<a href="https://colab.research.google.com/github/SarthakGupta345/PytorchLearning/blob/main/Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# pytorch autograd
print("Hello world")

Hello word;


In [2]:
import torch
print(torch.__version__)

2.9.0+cu126


In [9]:
x = torch.tensor(3.0, requires_grad=True)

In [17]:
y = x**2
print(y)


tensor(9., grad_fn=<PowBackward0>)


In [18]:
x

tensor(3., requires_grad=True)

In [19]:
y.backward()


In [20]:
x.grad

tensor(12.)

In [29]:
#examples 2
x = torch.rand(3,requires_grad=True)
y = x**2
z = torch.sin(y)

In [23]:
x,y,z

(tensor([8.5750e-01, 4.2224e-04, 6.1753e-01], requires_grad=True),
 tensor([7.3530e-01, 1.7829e-07, 3.8135e-01], grad_fn=<PowBackward0>),
 tensor([6.7081e-01, 1.7829e-07, 3.7217e-01], grad_fn=<SinBackward0>))

In [30]:
print(z)


tensor([0.2048, 0.8070, 0.8255], grad_fn=<SinBackward0>)


In [31]:
print(y)

tensor([0.2063, 0.9390, 0.9711], grad_fn=<PowBackward0>)


In [32]:
z.backwward()

AttributeError: 'Tensor' object has no attribute 'backwward'

In [33]:
x.grad

In [34]:
print(x.grad)

None


In [35]:
#Example 3

x = torch.tensor(6.7)
y = torch.tensor(0.0)

In [37]:
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [38]:
z = w*x+b

In [40]:
y_pred = torch.sigmoid(z)
print(y_pred)

tensor(0.9988, grad_fn=<SigmoidBackward0>)


In [42]:
loss = torch.binary_cross_entropy_with_logits(y_pred,y)
loss

tensor(1.3124, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)

In [43]:
loss.backward()

In [45]:
print(w.grad)
print(b.grad)

tensor(0.0060)
tensor(0.0009)


In [46]:
x = torch.tensor([1,2,3],dtype=torch.float32, requires_grad=True)

In [47]:
x

tensor([1., 2., 3.], requires_grad=True)

In [48]:
y = (x**2).mean()

In [49]:
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [50]:
y.backward()

In [51]:
print(x.grad)

tensor([0.6667, 1.3333, 2.0000])


In [65]:
#clear gradient
x = torch.tensor(2.0,requires_grad=True)
x

tensor(2., requires_grad=True)

In [70]:
y = x**2

In [71]:
y.backward()

In [72]:
print(x.grad)

tensor(4.)


In [69]:
x.grad.zero_()

tensor(0.)

In [73]:
x.requires_grad_(False)

tensor(2.)

In [74]:
z = x.detach()

In [78]:
with torch.no_grad():
    y = x**2
