<a href="https://colab.research.google.com/github/SarthakGupta345/PytorchLearning/blob/main/day6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print("hello world")
import numpy as np
import pandas as pd
import torch
print(torch.__version__)

hello world
2.9.0+cu126


In [3]:
from sklearn.datasets import make_classification


In [4]:
x,y = make_classification(
    n_samples=10,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)

In [5]:
x

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [6]:
x.shape

(10, 2)

In [7]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [8]:
y.shape

(10,)

In [9]:
x = torch.tensor(x,dtype=torch.float32)
y = torch.tensor(y, dtype=torch.float32)

In [10]:
x

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [11]:
y

tensor([1., 0., 0., 0., 0., 1., 1., 1., 1., 0.])

In [12]:
from torch.utils.data import Dataset,DataLoader


In [13]:
class Customdataset(Dataset):
  def __init__(self,features,labels):
     self.features = features
     self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self, index):
    return self.features[index],self.labels[index]



In [14]:
dataset = Customdataset(x,y)

In [15]:
len(dataset)

10

In [16]:
dataset[0]

(tensor([ 1.0683, -0.9701]), tensor(1.))

In [19]:
dataloader = DataLoader(dataset,batch_size=3,shuffle=True)

In [20]:
for batch_features, batch_labels in dataloader:
  print(batch_features)
  print(batch_labels)
  print('-'*50)

tensor([[-0.9382, -0.5430],
        [ 1.0683, -0.9701],
        [-1.9629, -0.9923]])
tensor([1., 1., 0.])
--------------------------------------------------
tensor([[-0.5872, -1.9717],
        [ 1.7273, -1.1858],
        [-2.8954,  1.9769]])
tensor([0., 1., 0.])
--------------------------------------------------
tensor([[-0.7206, -0.9606],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344]])
tensor([0., 1., 1.])
--------------------------------------------------
tensor([[-1.1402, -0.8388]])
tensor([0.])
--------------------------------------------------


In [21]:
import torch.nn as nn

In [22]:
#breast cancer dataset

In [23]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler


In [24]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [26]:
df.drop(columns='Unnamed: 32')

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0    ...        25.380          17.33           184.60      2019.0   
1    ...        24.990          23.41           158.80      1956.0   
2    ...        23.570          25.53           152.50      1709.0   
3    ...        14.910          26.50            98.87       567.7   
4    ...        22.540          16.67           152.20      1575.0   
..   ...           ...            ...              ...         ...   
564  ...        25.450          26.40           166.10      2027.0   
565  ...        23.690          38.25           155.00      1731.0   
566  ...        18.980          34.12           126.70      1124.0   
567  ...        25.740          39.42           184.60      1821.0   
568  ...         9.456          30.37            59.16       268.6   

     smoothness_worst  compactness_worst  concavity_worst  \
0             0.16220            0.66560           0.7119   
1             0.12380            0.18660           0.2416   
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...             ...                      ...  
564                0.2216       

In [33]:
df.head()


diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  texture_worst  perimeter_worst  area_worst  \
0         0.2419  ...          17.33           184.60      2019.0   
1         0.1812  ...          23.41           158.80      1956.0   
2         0.2069  ...          25.53           152.50      1709.0   
3         0.2597  ...          26.50            98.87       567.7   
4         0.1809  ...          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  Unnamed: 32  
0          0.4601                  0.11890          NaN  
1          0.2750                  0.08902          NaN  
2          0.3613                  0.08758          NaN  
3          0.6638                  0.17300          NaN  
4          0.2364                  0.07678          NaN  

[5 rows x 32 columns]

In [36]:
df.drop(columns='Unnamed: 32',inplace=True)

KeyError: "['Unnamed: 32'] not found in axis"

In [42]:
X_train,X_test ,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0], test_size=0.2)

In [38]:
X_train

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
9          12.46         24.04           83.97      475.9          0.11860   
327        12.03         17.93           76.09      446.0          0.07683   
40         13.44         21.58           86.18      563.0          0.08162   
394        12.10         17.72           78.07      446.2          0.10290   
107        12.36         18.54           79.01      466.7          0.08477   
..           ...           ...             ...        ...              ...   
57         14.71         21.59           95.55      656.9          0.11370   
69         12.78         16.49           81.37      502.5          0.09831   
236        23.21         26.97          153.50     1670.0          0.09509   
0          17.99         10.38          122.80     1001.0          0.11840   
334        12.30         19.02           77.88      464.4          0.08313   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
9             0.23960        0.227300             0.085430         0.2030   
327           0.03892        0.001546             0.005592         0.1382   
40            0.06031        0.031100             0.020310         0.1784   
394           0.09758        0.047830             0.033260         0.1937   
107           0.06815        0.026430             0.019210         0.1602   
..                ...             ...                  ...            ...   
57            0.13650        0.129300             0.081230         0.2027   
69            0.05234        0.036530             0.028640         0.1590   
236           0.16820        0.195000             0.123700         0.1909   
0             0.27760        0.300100             0.147100         0.2419   
334           0.04202        0.007756             0.008535         0.1539   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
9                   0.08243  ...         15.09          40.68   
327                 0.06070  ...         13.07          22.25   
40                  0.05587  ...         15.93          30.25   
394                 0.06161  ...         13.56          25.80   
107                 0.06066  ...         13.29          27.49   
..                      ...  ...           ...            ...   
57                  0.06758  ...         17.87          30.70   
69                  0.05653  ...         13.46          19.76   
236                 0.06309  ...         31.01          34.51   
0                   0.07871  ...         25.38          17.33   
334                 0.05945  ...         13.35          28.46   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
9              97.65       711.4            0.1853            1.05800   
327            82.74       523.4            0.1013            0.07390   
40            102.50       787.9            0.1094            0.20430   
394            88.33       559.5            0.1432            0.17730   
107            85.56       544.1            0.1184            0.19630   
..               ...         ...               ...                ...   
57            115.70       985.5            0.1368            0.42900   
69             85.67       554.9            0.1296            0.07061   
236           206.00      2944.0            0.1481            0.41260   
0             184.60      2019.0            0.1622            0.66560   
334            84.53       544.3            0.1222            0.09052   

     concavity_worst  concave points_worst  symmetry_worst  \
9           1.105000               0.22100          0.4366   
327         0.007732               0.02796          0.2171   
40          0.208500               0.11120          0.2994   
394         0.160300               0.06266          0.3049   
107         0.193700               0.08442          0.2983   
..               ...                   ...             ...   
57          0.358700               0.18340         

In [40]:
y_train

9      M
327    B
40     M
394    B
107    B
      ..
57     M
69     B
236    M
0      M
334    B
Name: diagnosis, Length: 455, dtype: object

In [43]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [46]:
X_train

array([[-0.77431879, -0.13471676, -0.80015596, ..., -0.80210639,
         0.67531517, -0.75952761],
       [ 0.1671744 , -1.05874458,  0.08376803, ..., -0.55406393,
        -0.91264368, -1.26757631],
       [ 0.07273891,  0.48358333,  0.06676949, ...,  0.09593143,
         0.20807625, -0.86750217],
       ...,
       [-0.98035985,  0.60222394, -0.98879827, ..., -0.62519264,
         0.11822261, -0.40377987],
       [-0.16478065, -1.4101033 , -0.19732975, ..., -0.53877882,
        -0.83749336,  0.19633134],
       [-1.37956441,  0.53834054, -1.36981429, ..., -1.18741213,
        -0.03371172, -0.03893953]])

In [47]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [48]:
y_train

array([0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,

In [49]:
y_train[0]

np.int64(0)

In [52]:
y_train.dtype

dtype('int64')

In [58]:
X_train = torch.from_numpy(X_train)
X_test = torch.from_numpy(X_test)
y_train = torch.from_numpy(y_train)
y_test = torch.from_numpy(y_test)

TypeError: expected np.ndarray (got Tensor)

In [62]:
y_test

tensor([1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
        0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
        0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
        0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0])

In [63]:
X_train.shape

torch.Size([455, 30])

In [64]:
from torch.utils.data import Dataset,DataLoader

In [65]:
class Customdataset(Dataset):
  def __init__(self,features,labels):
    self.features = features
    self.labels = labels
  def __len__(self):
    return len(self.features)
  def __getitem__(self, index):
    return self.features[index],self.labels[index]


In [67]:
train_dataset = Customdataset(X_train,y_train)
test_dataset = Customdataset(X_test,y_test)

In [68]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(train_dataset,batch_size=32,shuffle=True)

In [69]:
import torch.nn as nn

In [71]:

class MySimpleNN(nn.Module):
    def __init__(self, num_features):
        super(MySimpleNN, self).__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [72]:
learning_rate =0.1
epocs = 25

In [75]:
model = MySimpleNN(X_train.shape[1])
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

loss_function = nn.BCELoss()

In [76]:
for epocs in range(epocs):
  for batch_features, batch_labels in train_loader:

    y_pred = model(batch_features)

    loss = loss_function(y_pred,batch_labels.view(-1,1))

    optimizer.zero_grad()

    loss.backward()

    optimizer.step()


RuntimeError: mat1 and mat2 must have the same dtype, but got Double and Float